### ISSUE TITLE
JSON serialiser problem

### ISSUE THREAD

**Issue by harry-bridge** [newtheatre/nt-tickets#2]
```
[17/Dec/2015 18:36:22] "GET /book/1/ HTTP/1.1" 200 4682
[17/Dec/2015 18:36:24] "GET /api/0.1/remain?occ=1 HTTP/1.1" 200 79
Internal Server Error: /book/1/
Traceback (most recent call last):
  File "/Users/Harry/Envs/NTenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/Users/Harry/Envs/NTenv/lib/python2.7/site-packages/django/contrib/sessions/middleware.py", line 50, in process_response
    request.session.save()
  File "/Users/Harry/Envs/NTenv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 82, in save
    obj = self.create_model_instance(data)
  File "/Users/Harry/Envs/NTenv/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 68, in create_model_instance
    session_data=self.encode(data),
  File "/Users/Harry/Envs/NTenv/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 88, in encode
    serialized = self.serializer().dumps(session_dict)
  File "/Users/Harry/Envs/NTenv/lib/python2.7/site-packages/django/core/signing.py", line 95, in dumps
    return json.dumps(obj, separators=(',', ':')).encode('latin-1')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Ticket: test_show on 2016-12-17 at 16:31:12 for as> is not JSON serializable
```

**Comment by harry-bridge** [comment]
Fixed by changing the default serialiser to Pickle, a better solution would be nice
